[versions]
agp = "8.3.0"
org-jetbrains-kotlin-android = "1.9.22"
compose = "2024.02.02"
core-ktx = "1.12.0"
coroutines = "1.8.0"
annotation = "1.7.1"
appauth = "0.11.1"
appcompat = "1.6.1"
flexbox = "3.0.0"
fragment = "1.6.2"
layout = "2.1.4"
glide = "4.16.0"
hilt = "2.51"
hilt-compiler = "1.2.0"
hilt-work = "1.2.0"
junit = "4.13.2"
kapt = "1.9.22"
ksp = "1.9.22-1.0.17"
lifecycle = "2.7.0"
markdown = "4.6.2"
material = "1.11.0"
media3 = "1.3.0"
navigation = "2.7.7"
photoview = "2.3.0"
preference = "1.2.1"
recyclerview = "1.3.2"
retrofit = "2.9.0"
room = "2.6.1"
swiperefresh = "1.2.0-alpha01"
test-ext = "1.1.5"
test-espresso = "3.5.1"
timber = "5.0.1"
work = "2.9.0"
viewpager2 = "1.0.0"
okhttp = "4.12.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref ="appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
androidx-compose-material = { group = "androidx.compose.material3", name = "material3" }
androidx-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "layout" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-swiperefresh = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso" }
androidx-viewpager = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compiler-kapt = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
markdown = { group = "io.noties.markwon", name = "core", version.ref = "markdown" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
appauth = { group = "net.openid", name = "appauth", version.ref = "appauth" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-jackson = { group = "com.squareup.retrofit2", name = "converter-jackson", version.ref = "retrofit" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-okhttp = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

[bundles]
